### ISSUE TITLE
Improvement suggestions for shuffle

### ISSUE THREAD

**Issue by MarkusKramer** [gazolla/Kotlin-Algorithm#4]
I was looking for code to do shuffle. I feel there are two problems with your solution:
1. the function mutates the list given to it (and sort of pretends that it didn't by returning the result of the shuffle additionally as it's return value)
2. it doesn't use existing code for shuffling

I wrote this code for my project:

    /**
     * Returns a randomized list.
     */
    fun <T> Iterable<T>.shuffle(seed: Long? = null): List<T> {
        val list = this.toMutableList()
        val random = if (seed != null) Random(seed) else Random()
        Collections.shuffle(list, random)
        return list
    }

It reuses existing code to do the shuffling and can be called like other kotlin collection functions.

**Comment by gazolla** [comment]
Thanks Marcus ! Appreciate your contribution ! Project updated !
